# -*- coding: utf-8 -*-
"""Conheça o Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import numpy as np
try:
  qnotas = int(input("Digite a quantidade de notas para o cálculo da média e da situação acadêmica: "))
  notas = np.zeros(qnotas)

  while qnotas <= 0:
      print("Quantidade de notas inválida, apenas números maiores que 0")
      qnotas = int(input("Digite a quantidade de notas para o cálculo da média e da situação acadêmica: "))

  print(f"Digite {qnotas} notas")

  for i in range(qnotas):
    notas[i] = int(input(f"Digite a {i+1}ª nota: "))

    while notas[i] < 0 or notas[i] > 100:
      print("Nota inválida, apenas números positivos entre 0 e 100")
      notas[i] = int(input(f"Digite a {i+1}ª nota: "))

  med = np.mean(notas)
  maior = np.max(notas)
  menor = np.min(notas)

  print(f"A média é = {med:.1f}")
  print(f"A maior nota foi = {maior}")
  print(f"A menor nota foi = {menor}")

  if med >= 70:
    print("Resultado = Aprovado")
  elif 40 <= med < 70:
    print("Resultado = Exame Final")
  else:
    print("Resultado = Reprovado")
except ValueError:
  print("Quantidade de notas inválida, apenas números inteiros podem ser admitidos")